Repository AY2122S2-TIC4002-F18-6/tp2, pull requests merged in 2022-04, with the labels that each got.

#35 Add post and add client implementation
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SendCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CommonRegexPattern.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/post/PostDate.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: Function

#47 Bug Fixing: Addcommand displaying wrong feedback when trying to add post
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: bug

#50 update ruiting PPP.md
  docs/team/ruiting1.md
Labels: documentation

#53 send command bug fix and UI improve
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/SendCommand.java
  src/main/java/seedu/address/model/post/UniquePostList.java
  src/main/resources/view/MainWindow.fxml
Labels: bug

#56 implement mass delete for delete client and post
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/post/UniquePostList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: enhancement, Function

#55 Implemented Edit function for Post list.
  data/addressbook.json
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/address/model/post/Post.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: Function
